services:
  carflow:
    build: .
    container_name: carflow
    env_file:
      - .env

    command: >
      sh -c "
      python manage.py migrate &&
      python manage.py collectstatic --noinput &&
      gunicorn project.wsgi:application --bind 0.0.0.0:8002
      "

    environment:
      DEBUG: "0"
      SECRET_KEY: "${SECRET_KEY}"
      ALLOWED_HOSTS: "car.alsajana.site,localhost,127.0.0.1"
      CSRF_TRUSTED_ORIGINS: "https://car.alsajana.site"
      QR_PUBLIC_BASE_URL: "https://car.alsajana.site"
      SERVE_MEDIA: "1"

      DB_ENGINE: "${DB_ENGINE:-django.db.backends.sqlite3}"
      DB_NAME: "${DB_NAME:-/app/data/db.sqlite3}"
      DB_USER: "${DB_USER:-}"
      DB_PASSWORD: "${DB_PASSWORD:-}"
      DB_HOST: "${DB_HOST:-}"
      DB_PORT: "${DB_PORT:-}"

    volumes:
      - media:/app/media
      - staticfiles:/app/staticfiles
      - db_data:/app/data

    ports:   # 👈 مؤقت للاختبار فقط
      - "8002:8002"

    restart: unless-stopped


volumes:
  staticfiles:
  media:
  db_data: