# Generated by Django 5.2.11 on 2026-04-28 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_employee_first_name_employee_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='bio',
            field=models.TextField(blank=True, default=''),
        ),
    ]
