# Generated by Django 5.2.11 on 2026-04-29 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_employee_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='license_type',
            field=models.CharField(blank=True, choices=[('Private License', 'Private License'), ('Light License', 'Light License'), ('Heavy License', 'Heavy License')], max_length=20, null=True),
        ),
    ]
