# Generated by Django 5.2.11 on 2026-04-29 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_employee_date_of_birth_employee_license_type'),
    ]

    def _copy_employee_license(apps, schema_editor):
        Employee = apps.get_model("staff", "Employee")
        EmployeeLicense = apps.get_model("staff", "EmployeeLicense")

        for emp in Employee.objects.all().iterator():
            EmployeeLicense.objects.update_or_create(
                employee_id=emp.pk,
                defaults={
                    "license_number": getattr(emp, "license_number", None),
                    "license_type": getattr(emp, "license_type", None),
                    "license_expiry": getattr(emp, "license_expiry", None),
                },
            )

    def _noop(apps, schema_editor):
        return

    operations = [
        migrations.CreateModel(
            name='EmployeeLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.CharField(blank=True, max_length=50, null=True)),
                ('license_type', models.CharField(blank=True, choices=[('Private License', 'Private License'), ('Light License', 'Light License'), ('Heavy License', 'Heavy License')], max_length=20, null=True)),
                ('license_expiry', models.DateField(blank=True, null=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='license', to='staff.employee')),
            ],
        ),
        migrations.RunPython(_copy_employee_license, _noop),
        migrations.RemoveField(
            model_name='employee',
            name='license_expiry',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='license_number',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='license_type',
        ),
    ]
