# Generated by Django 5.2.11 on 2026-04-13 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fleet', '0016_car_current_mileage'),
        ('maintenance', '0005_maintenancecategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingMaintenanceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Submitted At')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20, verbose_name='Status')),
                ('submitter_name', models.CharField(blank=True, max_length=100, verbose_name='Submitter Name')),
                ('submitter_contact', models.CharField(blank=True, max_length=100, verbose_name='Submitter Contact')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Rejection Reason')),
                ('raw_data', models.JSONField(blank=True, null=True, verbose_name='Raw Data')),
                ('description', models.TextField(verbose_name='Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='pending_maintenance_reports/', verbose_name='Maintenance Image')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_%(class)s_requests', to='fleet.car', verbose_name='Car')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maintenance.maintenancecategory', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Pending Maintenance Report',
                'verbose_name_plural': 'Pending Maintenance Reports',
                'ordering': ['-submitted_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PendingMileageReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Submitted At')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20, verbose_name='Status')),
                ('submitter_name', models.CharField(blank=True, max_length=100, verbose_name='Submitter Name')),
                ('submitter_contact', models.CharField(blank=True, max_length=100, verbose_name='Submitter Contact')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Rejection Reason')),
                ('raw_data', models.JSONField(blank=True, null=True, verbose_name='Raw Data')),
                ('mileage', models.PositiveIntegerField(verbose_name='Mileage')),
                ('image', models.ImageField(blank=True, null=True, upload_to='pending_mileage_reports/', verbose_name='Odometer Image')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_%(class)s_requests', to='fleet.car', verbose_name='Car')),
            ],
            options={
                'verbose_name': 'Pending Mileage Report',
                'verbose_name_plural': 'Pending Mileage Reports',
                'ordering': ['-submitted_at'],
                'abstract': False,
            },
        ),
    ]
