# Generated by Django 5.2.11 on 2026-04-13 08:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pending_requests', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.PositiveIntegerField()),
                ('request_type', models.CharField(max_length=20)),
                ('action', models.CharField(choices=[('accepted', 'Accepted'), ('rejected', 'Rejected'), ('edited', 'Edited'), ('deleted', 'Deleted')], max_length=20)),
                ('acted_at', models.DateTimeField(auto_now_add=True)),
                ('details', models.TextField(blank=True)),
                ('acted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Request Log',
                'verbose_name_plural': 'Request Logs',
                'ordering': ['-acted_at'],
            },
        ),
    ]
