# Generated by Django 5.2.11 on 2026-04-13 09:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pending_requests', '0002_requestlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requestlog',
            options={'ordering': ['-acted_at'], 'permissions': [('approve_pending_requests', 'Can approve pending requests')], 'verbose_name': 'Request Log', 'verbose_name_plural': 'Request Logs'},
        ),
        migrations.AddField(
            model_name='pendingmaintenancereport',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pendingmaintenancereport',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pendingmaintenancereport',
            name='level1_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pendingmaintenancereport',
            name='level1_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_level1_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pendingmaintenancereport',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pendingmaintenancereport',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_rejected', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pendingmaintenancereport',
            name='submitter_address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Submitter Address'),
        ),
        migrations.AddField(
            model_name='pendingmaintenancereport',
            name='title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='pendingmileagereport',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pendingmileagereport',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pendingmileagereport',
            name='level1_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pendingmileagereport',
            name='level1_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_level1_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pendingmileagereport',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pendingmileagereport',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_rejected', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pendingmileagereport',
            name='submitter_address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Submitter Address'),
        ),
        migrations.AlterField(
            model_name='pendingmaintenancereport',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('level1_approved', 'Level 1 Approved'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='pendingmileagereport',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('level1_approved', 'Level 1 Approved'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='requestlog',
            name='action',
            field=models.CharField(choices=[('accepted', 'Accepted'), ('level1_approved', 'Level 1 Approved'), ('rejected', 'Rejected'), ('edited', 'Edited'), ('deleted', 'Deleted')], max_length=20),
        ),
        migrations.CreateModel(
            name='PendingMaintenanceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pending_maintenance_reports/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='pending_requests.pendingmaintenancereport')),
            ],
        ),
    ]
