# Generated by Django 5.2.11 on 2026-05-31 09:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0021_branch_branchdocument'),
        ('maintenance', '0006_maintenancerequest_branch_and_more'),
        ('pending_requests', '0004_remove_level1_approval'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingmaintenancereport',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_%(class)s_requests', to='fleet.branch', verbose_name='Branch'),
        ),
        migrations.AddField(
            model_name='pendingmileagereport',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_%(class)s_requests', to='fleet.branch', verbose_name='Branch'),
        ),
        migrations.AlterField(
            model_name='pendingmaintenancereport',
            name='car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_%(class)s_requests', to='fleet.car', verbose_name='Car'),
        ),
        migrations.AlterField(
            model_name='pendingmileagereport',
            name='car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_%(class)s_requests', to='fleet.car', verbose_name='Car'),
        ),
        migrations.AddConstraint(
            model_name='pendingmaintenancereport',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('car__isnull', False), ('branch__isnull', True)), models.Q(('car__isnull', True), ('branch__isnull', False)), _connector='OR'), name='pending_maintenance_requires_exactly_one_target'),
        ),
        migrations.AddConstraint(
            model_name='pendingmileagereport',
            constraint=models.CheckConstraint(condition=models.Q(('car__isnull', False), ('branch__isnull', True)), name='pending_mileage_requires_car'),
        ),
    ]
