from django.urls import path
from .views import (
    BranchCreateView,
    BranchDeleteView,
    BranchDetailView,
    BranchDocumentCreateView,
    BranchDocumentDeleteView,
    BranchDocumentDetailView,
    BranchDocumentUpdateView,
    BranchListView,
    BranchUpdateView,
    CarListView,
    CarMapView,
    CarDetailView,
    CarImageUploadView,
    CarConditionCreateView,
    CarCreateView,
    CarUpdateView,
    CarDeleteView,
    CarDocumentCreateView,
    CarDocumentDetailView,
    CarDocumentUpdateView,
    CarDocumentDeleteView,
    CarEventCreateView,
    CarCostCreateView,
    CarHandoverView,
    CarReturnView,
    CarAccidentCreateView,
    CarAccidentDetailView,
    CarAccidentUpdateView,
    CarAccidentDeleteView,
    CarHandoverEventDetailView,
    CarReturnEventDetailView,
    CarHandoverEventEditView,
    CarHandoverEventDeleteView,
    CarHandoverEventPDFView,
    CarHandoverVoucherPDFView,
    CarHandoverPrintView,
)

app_name = "fleet"

urlpatterns = [
    path("", CarListView.as_view(), name="car_index"),
    path("cars/", CarListView.as_view(), name="car_list"),
    path("cars/create/", CarCreateView.as_view(), name="car_create"),
    path("cars/map/", CarMapView.as_view(), name="car_map"),
    path("cars/<int:pk>/", CarDetailView.as_view(), name="car_detail"),
    path("cars/<int:pk>/edit/", CarUpdateView.as_view(), name="car_edit"),
    path("cars/<int:pk>/delete/", CarDeleteView.as_view(), name="car_delete"),
    path("cars/<int:pk>/images/upload/", CarImageUploadView.as_view(), name="car_image_upload"),
    path("cars/<int:pk>/conditions/new/", CarConditionCreateView.as_view(), name="car_condition_create"),
    path("cars/<int:pk>/documents/new/", CarDocumentCreateView.as_view(), name="car_document_create"),
    path("cars/<int:car_pk>/documents/<int:doc_pk>/", CarDocumentDetailView.as_view(), name="car_document_detail"),
    path("cars/<int:car_pk>/documents/<int:doc_pk>/edit/", CarDocumentUpdateView.as_view(), name="car_document_edit"),
    path("cars/<int:car_pk>/documents/<int:doc_pk>/delete/", CarDocumentDeleteView.as_view(), name="car_document_delete"),
    path("cars/<int:pk>/events/new/", CarEventCreateView.as_view(), name="car_event_create"),
    path("cars/<int:pk>/costs/new/", CarCostCreateView.as_view(), name="car_cost_create"),
    path("cars/<int:pk>/handover/", CarHandoverView.as_view(), name="car_handover"),
    path("cars/<int:pk>/return/", CarReturnView.as_view(), name="car_return"),
    path("cars/<int:pk>/accidents/new/", CarAccidentCreateView.as_view(), name="car_accident_create"),
    path("cars/<int:car_pk>/accidents/<int:event_pk>/", CarAccidentDetailView.as_view(), name="car_accident_detail"),
    path("cars/<int:car_pk>/accidents/<int:event_pk>/edit/", CarAccidentUpdateView.as_view(), name="car_accident_edit"),
    path("cars/<int:car_pk>/accidents/<int:event_pk>/delete/", CarAccidentDeleteView.as_view(), name="car_accident_delete"),
    path("cars/<int:car_pk>/handovers/<int:event_pk>/", CarHandoverEventDetailView.as_view(), name="handover_detail"),
    path("cars/<int:car_pk>/returns/<int:event_pk>/", CarReturnEventDetailView.as_view(), name="return_detail"),
    path("cars/<int:car_pk>/handovers/<int:event_pk>/edit/", CarHandoverEventEditView.as_view(), name="handover_edit"),
    path("cars/<int:car_pk>/handovers/<int:event_pk>/delete/", CarHandoverEventDeleteView.as_view(), name="handover_delete"),
    path("cars/<int:car_pk>/handovers/<int:event_pk>/pdf/", CarHandoverEventPDFView.as_view(), name="handover_pdf"),
    path("cars/<int:car_pk>/handovers/<int:event_pk>/voucher-pdf/", CarHandoverVoucherPDFView.as_view(), name="handover_voucher_pdf"),
    path("cars/<int:car_pk>/handovers/<int:event_pk>/print/", CarHandoverPrintView.as_view(), name="handover_print"),

    path("branches/", BranchListView.as_view(), name="branch_list"),
    path("branches/create/", BranchCreateView.as_view(), name="branch_create"),
    path("branches/<int:pk>/", BranchDetailView.as_view(), name="branch_detail"),
    path("branches/<int:pk>/edit/", BranchUpdateView.as_view(), name="branch_edit"),
    path("branches/<int:pk>/delete/", BranchDeleteView.as_view(), name="branch_delete"),
    path("branches/<int:pk>/documents/new/", BranchDocumentCreateView.as_view(), name="branch_document_create"),
    path("branches/<int:branch_pk>/documents/<int:doc_pk>/", BranchDocumentDetailView.as_view(), name="branch_document_detail"),
    path("branches/<int:branch_pk>/documents/<int:doc_pk>/edit/", BranchDocumentUpdateView.as_view(), name="branch_document_edit"),
    path("branches/<int:branch_pk>/documents/<int:doc_pk>/delete/", BranchDocumentDeleteView.as_view(), name="branch_document_delete"),
]
