# Generated by Django 5.2.11 on 2026-04-04 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_region_driverassignment_region'),
        ('staff', '0003_employee_first_name_employee_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverassignment',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_assignments', to='staff.employee'),
        ),
    ]
