# Generated by Django 5.2.11 on 2026-05-03 08:05

from django.db import migrations, models


def seed_departments(apps, schema_editor):
    Department = apps.get_model("accounts", "Department")
    defaults = [
        ("operations", "التشغيل", "Operations"),
        ("administration", "الإدارة", "Administration"),
        ("manufacturing", "التصنيع", "Manufacturing"),
    ]
    for code, name_ar, name_en in defaults:
        Department.objects.update_or_create(
            code=code,
            defaults={"name_ar": name_ar, "name_en": name_en, "is_active": True},
        )


def noop(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_driverassignment_driver'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name_ar', models.CharField(max_length=64)),
                ('name_en', models.CharField(blank=True, max_length=64)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name_ar'],
            },
        ),
        migrations.RunPython(seed_departments, noop),
    ]
