# Generated by Django 5.2.11 on 2026-02-22 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['-created_at'], 'verbose_name': 'Car', 'verbose_name_plural': 'Cars'},
        ),
        migrations.RemoveField(
            model_name='car',
            name='current_mileage',
        ),
        migrations.RemoveField(
            model_name='car',
            name='location_lat',
        ),
        migrations.RemoveField(
            model_name='car',
            name='location_lon',
        ),
        migrations.RemoveField(
            model_name='car',
            name='make',
        ),
        migrations.RemoveField(
            model_name='car',
            name='vin',
        ),
        migrations.AddField(
            model_name='car',
            name='brand',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='current_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='car',
            name='current_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude'),
        ),
        migrations.AddField(
            model_name='car',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='car',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(max_length=64, verbose_name='Model'),
        ),
        migrations.AlterField(
            model_name='car',
            name='plate_number',
            field=models.CharField(db_index=True, max_length=16, unique=True, verbose_name='Plate Number'),
        ),
        migrations.AlterField(
            model_name='car',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('maintenance', 'Maintenance'), ('inactive', 'Inactive')], db_index=True, default='active', max_length=16, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.PositiveIntegerField(verbose_name='Year'),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['is_active'], name='fleet_car_is_acti_8a00b5_idx'),
        ),
    ]
