# Generated by Django 5.2.11 on 2026-03-07 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0002_alter_car_options_remove_car_current_mileage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('condition', models.CharField(choices=[('active', 'Active'), ('maintenance', 'Maintenance'), ('inactive', 'Inactive')], default='active', max_length=64, verbose_name='Condition')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='CarRecordImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='car_record_images/')),
                ('caption', models.CharField(blank=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='carimage',
            name='car',
        ),
        migrations.RemoveIndex(
            model_name='carcondition',
            name='fleet_carco_car_id_e55360_idx',
        ),
        migrations.AddField(
            model_name='car',
            name='inspection_expiry_date',
            field=models.DateField(blank=True, null=True, verbose_name='Periodic Inspection Expiry Date'),
        ),
        migrations.AddField(
            model_name='car',
            name='license_expiry_date',
            field=models.DateField(blank=True, null=True, verbose_name='License Expiry Date'),
        ),
        migrations.AddField(
            model_name='car',
            name='license_number',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Car License Number'),
        ),
        migrations.AddField(
            model_name='car',
            name='transport_license_expiry_date',
            field=models.DateField(blank=True, null=True, verbose_name='Transport License Expiry Date'),
        ),
        migrations.AddField(
            model_name='car',
            name='transport_license_number',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Transport License Number'),
        ),
        migrations.AlterField(
            model_name='carcondition',
            name='recorded_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name='carrecord',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='fleet.car'),
        ),
        migrations.AddField(
            model_name='carrecordimage',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='fleet.carrecord'),
        ),
        migrations.DeleteModel(
            name='CarImage',
        ),
    ]
