# Generated by Django 5.2.11 on 2026-03-08 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0003_carrecord_carrecordimage_remove_carimage_car_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='car_images/')),
                ('caption', models.CharField(blank=True, max_length=128)),
                ('position', models.CharField(blank=True, choices=[('front', 'Front'), ('left', 'Left'), ('right', 'Right'), ('rear', 'Rear'), ('interior', 'Interior')], max_length=16, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='fleet.car')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
