# Generated by Django 5.2.11 on 2026-03-09 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_region_driverassignment_region'),
        ('fleet', '0004_carimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cars', to='accounts.region'),
        ),
    ]
