# Generated by Django 5.2.11 on 2026-03-14 23:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0005_car_region'),
        ('staff', '0002_alter_employee_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('start_odometer', models.PositiveIntegerField()),
                ('end_odometer', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='CarDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('license', 'License'), ('transport_license', 'Transport License'), ('insurance', 'Insurance'), ('inspection', 'Inspection')], max_length=32)),
                ('number', models.CharField(max_length=100)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='car_documents/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('inspection', 'Inspection'), ('handover', 'Handover'), ('return', 'Return'), ('maintenance', 'Maintenance'), ('accident', 'Accident'), ('status_change', 'Status Change')], max_length=32)),
                ('odometer', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CarEventImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='car_events/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='carcondition',
            name='car',
        ),
        migrations.RemoveField(
            model_name='carrecord',
            name='car',
        ),
        migrations.RemoveField(
            model_name='carrecordimage',
            name='record',
        ),
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['plate_number']},
        ),
        migrations.AlterModelOptions(
            name='carimage',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='car',
            name='fleet_car_status_d0b34f_idx',
        ),
        migrations.RemoveIndex(
            model_name='car',
            name='fleet_car_plate_n_07c9d0_idx',
        ),
        migrations.RemoveIndex(
            model_name='car',
            name='fleet_car_is_acti_8a00b5_idx',
        ),
        migrations.RemoveField(
            model_name='car',
            name='current_latitude',
        ),
        migrations.RemoveField(
            model_name='car',
            name='current_longitude',
        ),
        migrations.RemoveField(
            model_name='car',
            name='inspection_expiry_date',
        ),
        migrations.RemoveField(
            model_name='car',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='car',
            name='license_expiry_date',
        ),
        migrations.RemoveField(
            model_name='car',
            name='license_number',
        ),
        migrations.RemoveField(
            model_name='car',
            name='transport_license_expiry_date',
        ),
        migrations.RemoveField(
            model_name='car',
            name='transport_license_number',
        ),
        migrations.RemoveField(
            model_name='car',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='carimage',
            name='caption',
        ),
        migrations.AddField(
            model_name='car',
            name='vin',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.CharField(blank=True, default='Toyota', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='car',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='plate_number',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('assigned', 'Assigned'), ('maintenance', 'Maintenance'), ('inactive', 'Inactive')], db_index=True, default='available', max_length=20),
        ),
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='carimage',
            name='image',
            field=models.ImageField(default='Toyota', upload_to='car_images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carimage',
            name='position',
            field=models.CharField(blank=True, choices=[('front', 'Front'), ('rear', 'Rear'), ('left', 'Left'), ('right', 'Right'), ('interior', 'Interior')], default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carassignment',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='fleet.car'),
        ),
        migrations.AddField(
            model_name='carassignment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='carassignment',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_assignments', to='staff.employee'),
        ),
        migrations.AddField(
            model_name='cardocument',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='fleet.car'),
        ),
        migrations.AddField(
            model_name='carevent',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='fleet.car'),
        ),
        migrations.AddField(
            model_name='carevent',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='careventimage',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='fleet.carevent'),
        ),
        migrations.DeleteModel(
            name='CarCondition',
        ),
        migrations.DeleteModel(
            name='CarRecord',
        ),
        migrations.DeleteModel(
            name='CarRecordImage',
        ),
        migrations.AddIndex(
            model_name='cardocument',
            index=models.Index(fields=['car', 'document_type'], name='fleet_cardo_car_id_8c71a0_idx'),
        ),
        migrations.AddIndex(
            model_name='carevent',
            index=models.Index(fields=['car', '-created_at'], name='fleet_carev_car_id_e10541_idx'),
        ),
    ]
