# Generated by Django 5.2.11 on 2026-03-14 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0006_carassignment_cardocument_carevent_careventimage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
