# Generated by Django 5.2.11 on 2026-03-25 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0009_careventcondition'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='carcost',
            new_name='fleet_carco_car_id_d02650_idx',
            old_name='fleet_carcost_car_cat_cost_da_0c9b8c_idx',
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(choices=[('Sedan', 'Sedan'), ('Chiller Van', 'Chiller Van'), ('Reefer Truck', 'Reefer Truck'), ('Reefer Pickup', 'Reefer Pickup')], max_length=100, verbose_name='Vehicle Type'),
        ),
    ]
