# Generated by Django 5.2.11 on 2026-03-25 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0010_rename_fleet_carcost_car_cat_cost_da_0c9b8c_idx_fleet_carco_car_id_d02650_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='model',
        ),
        migrations.AddField(
            model_name='car',
            name='vehicle_type',
            field=models.CharField(choices=[('Sedan', 'Sedan'), ('Chiller Van', 'Chiller Van'), ('Reefer Truck', 'Reefer Truck'), ('Reefer Pickup', 'Reefer Pickup')], default='Sedan', max_length=100, verbose_name='Vehicle Type'),
        ),
    ]
