# Generated by Django 5.2.11 on 2026-03-25 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0011_remove_car_model_car_vehicle_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='vehicle_type',
            field=models.CharField(choices=[('Sedan', 'Sedan'), ('Reefer Van', 'Chiller Van'), ('Reefer Truck', 'Reefer Truck'), ('Reefer Pickup', 'Reefer Pickup')], default='Sedan', max_length=100, verbose_name='Vehicle Type'),
        ),
    ]
