# Generated by Django 5.2.11 on 2026-03-25 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0010_careventcondition_liability_percent'),
        ('fleet', '0012_alter_car_vehicle_type'),
    ]

    operations = [
    ]
