# Generated by Django 5.2.11 on 2026-04-01

import secrets

from django.db import migrations


def backfill_car_qr_token(apps, schema_editor):
    Car = apps.get_model("fleet", "Car")
    db_alias = schema_editor.connection.alias

    qs = Car.objects.using(db_alias).filter(qr_token__isnull=True)
    for car in qs.iterator():
        while True:
            token = secrets.token_urlsafe(32)
            if len(token) < 32:
                continue
            exists = Car.objects.using(db_alias).filter(qr_token=token).exists()
            if not exists:
                car.qr_token = token
                car.save(update_fields=["qr_token"])
                break


class Migration(migrations.Migration):
    dependencies = [
        ("fleet", "0014_car_qr_code_image_car_qr_enabled_car_qr_token"),
    ]

    operations = [
        migrations.RunPython(backfill_car_qr_token, migrations.RunPython.noop),
    ]

