# Generated by Django 5.2.11 on 2026-04-01 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0015_backfill_car_qr_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='current_mileage',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
