# Generated by Django 5.2.11 on 2026-04-01 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fleet', '0014_car_qr_code_image_car_qr_enabled_car_qr_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_car', models.ImageField(upload_to='vehicle_reports/car/')),
                ('image_odometer', models.ImageField(upload_to='vehicle_reports/odometer/')),
                ('mileage', models.PositiveIntegerField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_via_qr', models.BooleanField(db_index=True, default=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='fleet.car')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['vehicle', '-created_at'], name='reports_veh_vehicle_40b8ae_idx')],
            },
        ),
    ]
