# Generated by Django 5.2.11 on 2026-04-04 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleinspection',
            name='image_car',
            field=models.ImageField(blank=True, null=True, upload_to='vehicle_reports/car/'),
        ),
        migrations.AlterField(
            model_name='vehicleinspection',
            name='image_odometer',
            field=models.ImageField(blank=True, null=True, upload_to='vehicle_reports/odometer/'),
        ),
    ]
