# Generated by Django 5.2.11 on 2026-03-14 23:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maintenanceimage',
            options={},
        ),
        migrations.AlterModelOptions(
            name='maintenancerequest',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='maintenancerequest',
            name='maintenance_status_dfb247_idx',
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='odometer',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='maintenanceimage',
            name='caption',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('approved', 'Approved'), ('in_progress', 'In Progress'), ('completed', 'Completed')], db_index=True, default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
