# Generated by Django 5.2.11 on 2026-04-04 12:23

import maintenance.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0003_maintenancerequest_completion_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenanceimage',
            name='image',
            field=models.ImageField(upload_to=maintenance.models.maintenance_image_upload_path),
        ),
    ]
