# Generated by Django 5.2.11 on 2026-05-31 09:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0021_branch_branchdocument'),
        ('maintenance', '0005_maintenancecategory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerequest',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_requests', to='fleet.branch'),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_requests', to='fleet.car'),
        ),
        migrations.AddConstraint(
            model_name='maintenancerequest',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('car__isnull', False), ('branch__isnull', True)), models.Q(('car__isnull', True), ('branch__isnull', False)), _connector='OR'), name='maintenance_request_exactly_one_target'),
        ),
    ]
