# Generated by Django 5.2.11 on 2026-02-22 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('liters', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('odometer', models.PositiveIntegerField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_records', to='fleet.car')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['car', 'date'], name='fuel_fuelre_car_id_7c4661_idx')],
                'constraints': [models.UniqueConstraint(fields=('car', 'date', 'odometer'), name='unique_fuel_entry')],
            },
        ),
    ]
